Add supported token list for ethereum
bcnmy/docs pull request #145
Opened 2023-12-26 06:00 UTC by himanshugarg06

2023-12-26 08:42 UTC, divyaN73 commented on docs/supportedchains/supportedTokens.md
> +Our Paymaster not only allows you to sponsor gasless tokens for your users but also allows users to pay for tokens in supported ERC20 tokens. Below are supported tokens grouped by chain.
"Our Paymaster not only allows you to sponsor gasless tokens for your users"

it should be

"Our Paymaster not only allows you to sponsor transactions for your users"...

2023-12-26 09:03 UTC, livingrockrises commented on docs/supportedchains/supportedTokens.md
> +Please note that we will be reviewing DEX activity on each network to determine additional ERC20 token support on an ongoing basis.
we should add

Want to add a token? Please [contact us](mailto:support@biconomy.io) and we'll see what we can do.

do confirm contact email

2023-12-26 09:03 UTC, livingrockrises commented
I think the pair column is unnecessary

2023-12-26 09:12 UTC, livingrockrises commented
I think it also makes sense to add testnet tokens. later we can mention more about faucets or getting in touch to get tokens

2023-12-26 09:13 UTC, livingrockrises commented
we do support so manyy tokens on BSC mainnet. I expect list to be longer. can you double check in config file and with @divyaN73

2023-12-26 09:26 UTC, divyaN73 submitted a review, later dismissed

2023-12-26 09:33 UTC, divyaN73 commented
> we do support so manyy tokens on BSC mainnet. I expect list to be longer. can you double check in config file and with @divyaN73

cross checked on growthbook too, it showing 32 tokens approx. I'll get this checked from shurti next week

2023-12-26 12:58 UTC, NunoFilipeSantos commented on docs/supportedchains/supportedTokens.md
> +Our Paymaster not only allows you to sponsor transactions for your users but also allows users to pay for transactions using ERC20 tokens. Below are supported tokens list grouped by chain.
```suggestion
Our Paymaster not only allows you to sponsor transactions for your users but also allows users to pay for transactions using ERC20 tokens. Below are the supported tokens list grouped by chain.
```

2023-12-26 12:58 UTC, NunoFilipeSantos requested changes
"the" missing.

2023-12-27 06:03 UTC, himanshugarg06 commented
> I think it also makes sense to add testnet tokens. later we can mention more about faucets or getting in touch to get tokens

Will create a new task for these.

2023-12-27 06:38 UTC, merged