Add Dynamic as a signer guide
bcnmy/docs pull request #156
Opened 2024-01-10 01:44 UTC by matthew1809

2024-01-15 19:20 UTC, AmanRaj1608 commented on docs/Account/signers/dynamic.md
> +:::
Need to break the first tip, this is creating a nested tip
<img width="780" alt="image" src="https://github.com/bcnmy/docs/assets/42104907/2f3fdc51-8d71-4845-8665-d7fb5e2a9c67">

2024-01-15 19:20 UTC, AmanRaj1608 commented on yarn.lock
Why `yarn.lock` change is needed?

2024-01-15 19:22 UTC, AmanRaj1608 reviewed
Overall LGTM, can simplify the sub numbering maybe. cc: @livingrockrises @himanshugarg06

2024-01-15 22:15 UTC, matthew1809 commented on yarn.lock
reverted any changes, not sure why it did

2024-01-16 08:27 UTC, AmanRaj1608 approved these changes
LGTM!

2024-01-16 10:24 UTC, NunoFilipeSantos commented on docs/Account/signers/dynamic.md
> +Now you're ready to allow the user to authorize actions from their Biconomy smart account by signing messages with their Dynamic wallet. This is done by initializing a `ECDSAOwnershipValidationModule
```suggestion
Now you're ready to allow the user to authorize actions from their Biconomy smart account by signing messages with their Dynamic wallet. This is done by initializing a `ECDSAOwnershipValidationModule` for the user's smart account and passing in a signer from the user's wallet.
```

2024-01-16 10:25 UTC, NunoFilipeSantos commented on docs/Account/signers/dynamic.md
> +Once a user signs up through Dynamic, you can create a Biconomy smart account and use their Dynamic wallet as a signer for that new smart account. This means that the user will be able to user Bicono
```suggestion
Once a user signs up through Dynamic, you can create a Biconomy smart account and use their Dynamic wallet as a signer for that new smart account. This means that the user will be able to use Biconomy's account abstraction features out of the box! Just before you do that though, you need to follow two more steps:
```

2024-01-16 10:26 UTC, NunoFilipeSantos requested changes
2 typos left to fix.

2024-01-16 12:55 UTC, matthew1809 commented
> 2 typos left to fix.

Fixed @NunoFilipeSantos - thank you

2024-01-16 17:02 UTC, NunoFilipeSantos approved these changes
Thank you for fixing it. 😃

2024-01-17 06:40 UTC, merged