Partner docs
bcnmy/docs pull request #160
Opened 2024-01-14 22:13 UTC by B-Venkatesh7210

2024-01-18 11:18 UTC, livingrockrises commented
Please resolve conflicts. @B-Venkatesh7210 
cc @himanshugarg06

2024-01-19 10:23 UTC, himanshugarg06 commented
LGTM

2024-01-22 13:06 UTC, NunoFilipeSantos commented on partners/crosschain.md
> +We've established partnerships with leading crypto-to-crypto swap service providers and aggregators to facilitate a seamless integration of swap functionalities within our platform. Through their dev
```suggestion
We've established partnerships with leading crypto-to-crypto swap service providers and aggregators to facilitate a seamless integration of swap functionalities within our platform. Through their developer integration toolkits, users can now exchange cryptocurrencies directly within any app, website, or web plugin. This collaboration enables users to swap between various crypto assets without the need for multiple transactions or dealing with the intricacies of swapping different assets on separate platforms. It simplifies the process and ensures a convenient experience for managing their crypto portfolios. Please note that compliance with relevant regulatory requirements may apply to working with some of these providers.
```

2024-01-22 13:07 UTC, NunoFilipeSantos commented on partners/crosschain.md
> +> 💡 Using **Session Keys** within your app will eliminate the need for this step, and using our **Paymaster** will eliminate the need for the user to keep blockchain’s native token to complete the sw
```suggestion
> 💡 Using **Session Keys** within your app will eliminate the need for this step, and using our **Paymaster** will eliminate the need for the user to keep the blockchain’s native token to complete the swap.
```

2024-01-22 13:09 UTC, NunoFilipeSantos commented on partners/socialLogins.md
> +We've rounded up the best social login options out there, all in one spot for you. The Biconomy stack works smoothly with these logins, supporting easy integration. When developers pick wallets for t
```suggestion
# Social Login - Signers for your SA

Every account generated on a blockchain has a logic that allows us to cryptographically sign transactions using our private keys. Authentication services like Particle, Web3Auth, and wallet applications such as Metamask provide us with easier options to manage private keys and initiate transactions.

As you might already know, there are two types of accounts i.e. Smart Accounts and Externally Owned Accounts (EOAs). A lot of web3 users have EOAs that they manage using their Metamask and other similar self-custodial wallet services.

Similar to EOAs, Smart Accounts also have a signer vis-a-vis a validation logic which can be set to an ECDSA signature. These ECDSA signatures can be generated using an associated private key. Developers have the flexibility to choose a singer to manage these private keys for the user. Services like Web3Auth, Particle, etc provide creative and more user-friendly ways like Passkeys, Social Login, and Emails to use the said private keys which are secured using different security methods like MPC, DKG, etc.

We've rounded up the best social login options out there, all in one spot for you. The Biconomy stack works smoothly with these logins, supporting easy integration. When developers pick wallets for their apps, they should think about things like security, cost, user experience, flexibility, privacy, and recoverability. Check out the table below to get a quick look at these factors.
```

2024-01-22 13:10 UTC, NunoFilipeSantos commented on partners/walletUiKit.md
> +The pictures below give you a peek into what the Obvious Embed UI looks like and the cool features it comes with.
```suggestion
Developers can now integrate Biconomy’s account abstraction-based wallet in their apps in just 5 minutes and a few lines of code. Our partners at Obvious have built out a UI kit on our existing infrastructure that removes the need for developers to build an in-app wallet UI experience for the user. The developers can now use the Obvious Embed for a smooth in-app Smart Account experience.

**What do dApps get by integrating with the Obvious Embed kit?**

- Obvious embed kit helps developers to build for both EOA & SCW by abstracting out complexities around gas fees.
- Standard signer & provider interface for EOA & SCW
- UI Kit for showing portfolio across multiple chains, including tokens, NFTs & transaction history
- UI Kit for 1-click swapping & bridging of tokens
- Customizations (colors & styles) that can be plugged into your dApp, as a popup or a separate tab, with minimal effort.
- [Obvious](https://www.obvious.technology/) as a wallet partner, built on top of Biconomy Account Abstraction SDK, users of your dApp can take their credentials and log in to Obvious Wallet for a complete wallet experience.

The pictures below give you a peek into what the Obvious Embed UI looks like and the cool features it comes with.
```

2024-01-22 13:10 UTC, NunoFilipeSantos requested changes
Small corrections.
@himanshugarg06 please also take a look before merging.

2024-01-23 09:24 UTC, himanshugarg06 approved these changes

2024-01-23 11:39 UTC, merged