fix bundler methods
bcnmy/docs pull request #221
Opened 2024-03-06 08:10 UTC by himanshugarg06

@arcticfloyd1984 can you help with the param definition and other details if any

2024-03-11 15:50 UTC, NunoFilipeSantos commented on docs/Bundler/integration.mdx
> +This guide solely focuses on the code to integrate the Bundler. To see how this interacts with other packages in the sdk you can view the [Smart Accounts Integration page](/Account/integration).
```suggestion
This guide solely focuses on the code to integrate the Bundler. To see how this interacts with other packages in the SDK you can view the [Smart Accounts Integration page](/Account/integration).
```

2024-03-11 15:51 UTC, NunoFilipeSantos reviewed
Please capitalize acronyms like SDK, URL.

2024-03-14 09:38 UTC, NunoFilipeSantos commented on docs/Bundler/integration.mdx
> +This guide focuses on the code to integrate the Bundler. To see how this interacts with other packages in the sdk you can view the [Smart Accounts Integration page](/Account/integration).
```suggestion
This guide focuses on the code to integrate the Bundler. To see how this interacts with other packages in the SDK you can view the [Smart Accounts Integration page](/Account/integration).
```

2024-03-14 09:39 UTC, NunoFilipeSantos commented on docs/Bundler/integration.mdx
> +Once initialized you will be able to pass this Bundler instance to the Smart Account configuration to use in conjunction with Smart Accounts. See our [tutorials](/tutorials) for in depth integrations
```suggestion
- bundlerUrl(`string`, required): bundler URL from the dashboard
- [userOpReceiptIntervals](https://bcnmy.github.io/biconomy-client-sdk/classes/Bundler.html#UserOpReceiptIntervals)(`object`, optional): The polling interval per chain for the tx receipt in milliseconds. The default value is 5 seconds.
- [userOpWaitForTxHashIntervals](https://bcnmy.github.io/biconomy-client-sdk/classes/Bundler.html#UserOpWaitForTxHashIntervals)(`object`, optional): The polling interval per chain for the tx result in milliseconds. The default value is 0.5 seconds.
- [userOpReceiptMaxDurationIntervals](https://bcnmy.github.io/biconomy-client-sdk/classes/Bundler.html#userOpReceiptMaxDurationIntervals)(`object`, optional): The maximum duration in milliseconds per chain to wait for the tx receipt. The default value is 30 seconds.
- [userOpWaitForTxHashMaxDurationIntervals](https://bcnmy.github.io/biconomy-client-sdk/classes/Bundler.html#UserOpWaitForTxHashMaxDurationIntervals)(`object`, optional): The maximum duration in milliseconds per chain to wait for the tx hash. The default value is 20 seconds.

**returns**
- [bundler](https://bcnmy.github.io/biconomy-client-sdk/classes/Bundler.html)(`Promise<Bundler>`): bundler instance

Once initialized you will be able to pass this Bundler instance to the Smart Account configuration to use in conjunction with Smart Accounts. See our [tutorials](/tutorials) for in-depth integrations of the Smart Account and Bundler.
```

2024-03-14 09:39 UTC, NunoFilipeSantos requested changes
Typos.

2024-03-15 05:46 UTC, arcticfloyd1984 approved these changes

2024-03-15 05:47 UTC, arcticfloyd1984 approved these changes

2024-03-15 05:47 UTC, arcticfloyd1984 commented on docs/Bundler/bundlermethods.md
> +This method is used to estimate gas for the userOp. It returns estimates for PreVerificationGas, VerificationGas, and CallGasLimit for a given UserOperation. It requires passing a semi-valid/ dummy s
Should be verificationGasLimit not VerificationGas
Can we also make it use camel casing for these variables?

2024-03-15 05:57 UTC, merged