feat: adds spending limits page
bcnmy/docs pull request #227
Opened 2024-03-11 13:29 UTC by malcodeman

2024-03-11 14:54 UTC, NunoFilipeSantos commented on versioned_docs/version-3.0/dashboard/paymasterRules.md
> +Navigate to the Paymaster you have created, then click rules and contract. If this is the first time you are adding a smart contract the page will look like this:
```suggestion
Navigate to the Paymaster you have created, then click `Rules` and `Contract`. If this is the first time you are adding a smart contract the page will look like this:
```

2024-03-11 14:55 UTC, NunoFilipeSantos commented on versioned_docs/version-3.0/dashboard/spendingLimits.md
> +Both the global and the user limit modals are very simiar and offer same options.
```suggestion
# Add a global limit

Navigate to the Paymaster you have created, then click `Rules` and `Spending`. 
If this is the first time you are adding a limit the page will look like this:

![new limit](../images/limits/new_limit.png)

Click on `Add limit ` inside the Global Limit card and the new global limit modal will appear.
Inside the modal you will be presented with the option of choosing:

- Threshold type (Gas Spend | Number of user operations)
- Threshold value
- Cycle duration (minimum 1 hour, maximum 23 hours)

After clicking `Create` the limit will be created.

![add global limit](../images/limits/global_limit_modal.png)

## Add a user limit

Click on `Add limit` inside User Limit card and the new user limit modal will appear.
Both the global and the user limit modals are very similar and offer the same options.
```

2024-03-11 14:55 UTC, NunoFilipeSantos requested changes
Some corrections needed.

2024-03-11 15:06 UTC, NunoFilipeSantos submitted a review, later dismissed
LGTM now. 😃

2024-03-12 07:06 UTC, himanshugarg06 commented on docs/dashboard/spendingLimits.md
> +# Add a global limit
```suggestion
# Spending limits
This feature allows you to set limits to the gas usage. You can define global limits or per-user quotas, specifying either transaction count or total gas consumption.

## Add a global limit
```

2024-03-12 07:07 UTC, himanshugarg06 requested changes
left one comment

2024-03-12 13:26 UTC, himanshugarg06 submitted a review, later dismissed

2024-03-14 16:55 UTC, NunoFilipeSantos commented on docs/dashboard/spendingLimits.md
> +Pausing/Activating a limit will not reset the cycle.
```suggestion
Please note that whenever the limit policy is edited (duration / threshold / threshold type), the cycle is reset, and the new cycle starts from the moment of edit.
Pausing/Activating a limit will not reset the cycle.
```

2024-03-15 08:53 UTC, himanshugarg06 approved these changes

2024-03-15 08:54 UTC, merged