add api integration tutorial
bcnmy/docs pull request #231
Opened 2024-03-12 10:01 UTC by himanshugarg06

2024-03-12 17:31 UTC, joepegler approved these changes

2024-03-13 10:11 UTC, NunoFilipeSantos requested changes
Changes needed.

2024-03-15 05:58 UTC, arcticfloyd1984 requested changes
- We can remove `console.log`, don't think they are needed. A dev can add them according to their need
- Rather than doing `const url=` in every method, set it on a global level and probably rename it to bundlerUrl for clarity, also use another testnet and not 80001 as it will be removed soon
- I have recommended some changes in User Sponsored cases, but they apply to all cases so do check it out.

2024-03-15 05:58 UTC, arcticfloyd1984 commented on docs/tutorials/apiIntegration/paymasterERC20.md
> +    id: 4545,
Use Date.now()

2024-03-15 05:58 UTC, arcticfloyd1984 commented on docs/tutorials/apiIntegration/paymasterERC20.md
> +    id: 4545,
Use Date.now()

2024-03-15 05:58 UTC, arcticfloyd1984 commented on docs/tutorials/apiIntegration/paymasterSponsored.md
> +    id: 4545,
Use Date.now()

2024-03-15 05:58 UTC, arcticfloyd1984 commented on docs/tutorials/apiIntegration/paymasterSponsored.md
> +    id: 4545,
Use Date.now()

2024-03-15 05:58 UTC, arcticfloyd1984 commented on docs/tutorials/apiIntegration/userSponsored.md
> +    id: 4545,
Use Date.now()

2024-03-15 05:58 UTC, arcticfloyd1984 commented on docs/tutorials/apiIntegration/userSponsored.md
> +    params: [userOpHash],
Use Date.now()

2024-03-15 05:58 UTC, arcticfloyd1984 commented on docs/tutorials/apiIntegration/userSponsored.md
> +      "params": [
This can be made cleaner by just doing this:
`"params": [partialUserOp, "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"]`

2024-03-15 10:42 UTC, arcticfloyd1984 requested changes

2024-03-15 10:42 UTC, arcticfloyd1984 commented on docs/tutorials/apiIntegration/userSponsored.md
> +}
BigNumberish and BytesLike types are a little confusing, they are very specific to ethers. I would suggest keeping it some generic type as people not using JS environment and not using ethers will get confused, so would suggest to keep like this:

```
type UserOperation = {
  sender: string; // hex or number in string
  nonce: string; // hex or number in string
  initCode: string; // hex or number in string
  callData: string; // hex or number in string
  callGasLimit: string; // hex or number in string
  verificationGasLimit: string; // hex or number in string
  preVerificationGas: string; // hex or number in string
  maxFeePerGas: string; // hex or number in string
  maxPriorityFeePerGas: string; // hex or number in string
  paymasterAndData: string; // hex or number in string
  signature: string; // hex or number in string
}
```

2024-03-15 11:39 UTC, arcticfloyd1984 approved these changes

2024-03-15 11:46 UTC, merged